'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { Brain, Sparkles, Activity, Link2, BookOpen, Clock } from 'lucide-react';
import Link from 'next/link';

export default function LearnPage() {
  const sections = [
    {
      icon: <Brain className="h-6 w-6 text-sky-500" />,
      title: 'What are Mudras?',
      content:
        'Mudras are physical hand postures and gestures historically used in yoga and meditation practices to channel energy. In a modern wellness context, they are simple hand exercises and finger-stretching positions that serve as active focal points to quiet the mind, stabilize posture, and increase somatic (body) awareness.',
    },
    {
      icon: <Activity className="h-6 w-6 text-sage-500" />,
      title: 'The Concept of Embodied Cognition',
      content:
        'Embodied Cognition is a concept in cognitive science stating that our thoughts, emotions, and decisions are not just generated by an isolated brain, but are deeply shaped by the physical posture and movements of our body. Pressing your hands together in Anjali Mudra, for instance, sends tactile signals of symmetry and alignment to the nervous system, helping downregulate stress responses and prime feelings of composure and centeredness.',
    },
    {
      icon: <Link2 className="h-6 w-6 text-accent-amber-dark dark:text-accent-amber" />,
      title: 'Somatosensory Mapping & Attention',
      content:
        'Your fingertips contain some of the highest densities of tactile nerve endings (mechanoreceptors) in the human body. In the brain\'s somatosensory cortex (often represented by the homunculus sensory map), the hands and fingers occupy a disproportionately large area. By holding specific configurations, you stimulate this rich neural real estate, providing a constant, low-level physical sensation that acts as a cognitive "anchor"—suppressing mind-wandering and helping you focus on the present moment.',
    },
    {
      icon: <Sparkles className="h-6 w-6 text-sky-400" />,
      title: 'Mindfulness & Tactile Anchors',
      content:
        'Mindfulness requires anchoring your attention to a physical sensation, typically the breath. For many, the breath can feel too abstract. A mudra provides a physical, tangible anchor. The gentle pressure of your index finger touching your thumb in Gyan Mudra provides constant, structural feedback. If your mind drifts into anxiety, the loss of finger pressure acts as an instant physical reminder to return to your practice.',
    },
    {
      icon: <Clock className="h-6 w-6 text-sage-500" />,
      title: 'Micro-Breaks & Ergonomic Habit Loops',
      content:
        'Modern screen schedules leave hands cramped and posture collapsed. Mudras offer a dual-benefit: they serve as structured mindfulness exercises and provide ergonomic stretch sessions. By linking mudras to existing habits—such as performing a 2-minute Gyan Mudra when your morning coffee brews, or holding Vayu Mudra during a Pomodoro screen break—you establish positive wellness routines that combat repetitive strain and mental fatigue.',
    },
  ];

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      {/* Title Header */}
      <div className="text-center mb-16">
        <h1 className="font-outfit text-3.5xl md:text-5xl font-extrabold text-sage-800 dark:text-sage-100">
          Understanding Mudras
        </h1>
        <p className="mt-4 text-sm text-sage-500 dark:text-sage-400 max-w-xl mx-auto leading-relaxed">
          How simple hand positions influence attention, breathing rhythms, and somatic composure through cognitive feedback.
        </p>
      </div>

      {/* Main Educational Sections */}
      <div className="space-y-8">
        {sections.map((sec, idx) => (
          <motion.div
            key={idx}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: idx * 0.08 }}
            className="p-6 md:p-8 rounded-2xl glass-effect border border-glass-border flex flex-col md:flex-row gap-5 items-start"
          >
            <div className="flex items-center justify-center p-3 rounded-xl bg-sage-50 dark:bg-sage-950/30 border border-sage-100 dark:border-sage-900/30 shrink-0">
              {sec.icon}
            </div>
            <div className="space-y-2">
              <h2 className="font-outfit text-lg font-bold text-sage-800 dark:text-sage-100">
                {sec.title}
              </h2>
              <p className="text-xs text-sage-600 dark:text-sage-350 leading-relaxed">
                {sec.content}
              </p>
            </div>
          </motion.div>
        ))}
      </div>

      {/* Bottom Call to Action */}
      <div className="mt-16 text-center bg-sky-500/5 dark:bg-sky-400/5 rounded-2xl border border-sky-400/10 p-8">
        <h3 className="font-outfit text-xl font-bold text-sage-800 dark:text-sage-100 mb-2">
          Experience the Practice
        </h3>
        <p className="text-xs text-sage-500 dark:text-sage-400 mb-6 max-w-md mx-auto">
          Explore the library to inspect individual hand positions, read their scientific analysis, and choose a gesture that matches your current goal.
        </p>
        <div className="flex flex-wrap justify-center gap-4">
          <Link
            href="/library"
            className="px-5 py-3 rounded-xl bg-sage-600 hover:bg-sage-700 text-white text-xs font-bold transition-all"
          >
            View Mudra Library
          </Link>
          <Link
            href="/practice"
            className="px-5 py-3 rounded-xl border border-sage-200 dark:border-sage-800 text-sage-700 dark:text-sage-350 hover:bg-sage-100/30 text-xs font-bold transition-all"
          >
            Go to Daily Practice
          </Link>
        </div>
      </div>
    </div>
  );
}
